// to generate a pick randomly, I used the Math.random() method to randomly generate numbers to target a string on the array. But since it only generates decimal numbers, in order to generate a whole number, I added Math.floor() method to round off the decimal.

function computerPlay() {
    const pick = ['rock', 'paper', 'scissors'];
    return pick[Math.floor(Math.random() * pick.length)];
}

// the prompt only appear once throughout the game when I assigned the variable playerSelection a prompt so i decided to create a function.
// function playerPlay() {
//    const pick = prompt("Choose among 'Rock, Paper, Scissors' as your weapon.").toLowerCase();
//    return pick;
// }


// for the function playRound we added two paramters playerSelection(generated by the input of the player) & computerSelection(is generated by the computerPlay() function we had created above). 

function playRound(playerSelection, computerSelection) {
   if (playerSelection === computerSelection) {
      alert(`It's a tie! you both picked ${playerSelection}`);
      return "tie";
   } else if (playerSelection !== "rock" && playerSelection !== "paper" && playerSelection !== "scissors"){
      alert(`You sure about using ${playerSelection} on a game of "Rock, Paper, Scissors"?`)
   } else if (playerSelection === "rock" && computerSelection === "scissors") {
      alert(`You win this round! ${playerSelection} beats ${computerSelection}`);
      return "playerWin";
   } else if (playerSelection === "paper" && computerSelection === "rock") {
      alert(`You win this round! ${playerSelection} beats ${computerSelection}`);
      return "playerWin";
   } else if (playerSelection === "scissors" && computerSelection === "paper") {
      alert(`You win this! ${playerSelection} beats ${computerSelection}`);
      return "playerWin";
   } else {
      alert(`You lose this round! ${computerSelection} beats ${playerSelection}`);
      return "botWin";
   }
}

const computerSelection = computerPlay();



function game() {
   let playerScore = 0;
   let botScore = 0;
   let gameWinner = '';
   
   for (let i = 0; i < 5; i++) {

      let playerSelection = prompt(`Round ${i+1}: Choose among "Rock, Paper, Scissors" as your weapon`).toLowerCase();
      let roundResult = playRound(playerSelection, computerPlay());

      if (roundResult === "playerWin" ) {
         playerScore++;
      } else if (roundResult === "botWin" ) {
         botScore++;
      }
   }

   if (playerScore > botScore) {
      gameWinner = 'You win!';
   } else if (botScore > playerScore) {
      gameWinner = 'You lose, Computer wins!';
   } else {
      gameWinner = 'Draw';
   }

   alert(`Player: ${playerScore}  |  Bot: ${botScore}`);

   if (gameWinner === 'Draw') {
      alert("There is no match winner, draw!");
   } else {
      alert(`${gameWinner}`);
   }
}

game();