// to generate a pick randomly, I used the Math.random() method to randomly generate numbers to target a string on the array. But since it only generates decimal numbers, in order to generate a whole number, I added Math.floor() method to round off the decimal.

function computerPlay() {
    const pick = ['rock', 'paper', 'scissors'];
    return pick[Math.floor(Math.random() * pick.length)];
}

function playerPlay() {
   const pick = prompt("Choose among 'Rock, Paper, Scissors' as your weapon.").toLowerCase();
   return pick;
}


// for the function playRound we added two paramters playerSelection(generated by the input of the player) & computerSelection(is generated by the computerPlay() function we had created above). 

function playRound(playerSelection, computerSelection) {
   if (playerSelection === computerSelection) {
      alert(`It's a tie! you both picked ${playerSelection}`);
      return "tie";
   } else if (playerSelection === "rock" && computerSelection === "scissors") {
      alert("You win! Rock beats Scissors");
      return true;
   } else if (playerSelection === "paper" && computerSelection === "rock") {
      alert("You win! Paper beats Rock");
      return true;
   } else if (playerSelection === "scissors" && computerSelection === "paper") {
      alert("You win! Scissors beats Paper");
      return true;
   } else {
      alert(`You lose! ${computerSelection} beats ${playerSelection}`);
      return false;
   }
}

let playerSelection = playerPlay();
const computerSelection = computerPlay();



function game() {
   let playerScore = 0;
   let botScore = 0;
   let roundResult = '';
   
   
   for (let i = 0; i < 5; i++) {
      let roundResult = playRound(playerPlay(), computerPlay());
      if (roundResult === true ) {
         playerScore++;
      } else if (roundResult === false ) {
         botScore++;
      }
   }


   if (playerScore > botScore) {
      roundResult = 'You win!';
   } else if (botScore > playerScore) {
      roundResult = 'You lose!';
   } else {
      roundResult = 'Draw';
   }

   alert(`Player: ${playerScore} | Bot: ${botScore}`);

   if (roundResult === 'Draw') {
      alert("There is no match winner, draw!");
   } else {
      alert(`${roundResult}`);
   }
}

game();